### ISSUE TITLE
unsafe path to file

### ISSUE THREAD

**Issue by akroii** [pdir/amphtml-bundle#2] opened 2017-10-25 09:26 UTC
https://github.com/pdir/amphtml-bundle/blob/f35e50a5733d43af8d4a759fcb947d4bd97b5cdc/src/Resources/contao/classes/AmphtmlHooks.php#L86

path to file will not work correctly most of the time, use relative path to file

**Comment by MDevster** [comment] 2017-10-26 15:29
duplicate of #3

**Closed as completed by MDevster** 2017-10-26 15:29 UTC
